/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:da519b0a-8569-4075-aafe-43d722c85e1f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_b3QMo6XGH",
    "aws_user_pools_web_client_id": "3ken3fe28mli905dqdijndq6kq",
    "oauth": {}
};


export default awsmobile;
